### PR TITLE
Properties window - Ability to edit entities

### PR DESCRIPTION
**Pull request by Brett-Parker**
Added properties editing to the following items;

Format
Entity: editable items added

Line: LineWidth
PolyLine: LineWidth
Text: Height, Text
Arc: LineWidth, Radius
Rec: LineWidth

Radius doesn't seem to work for Circle, possibly to do with the way it is drawn? Arc works fine.

### CODE REVIEW

**Comment by Brett-Parker** [comment]
This is complete but relies on #147 and https://github.com/dubstar-04/Design-Core/pull/61

**Comment by dubstar-04** [comment]
> @dubstar-04 This is complete but relies on #147 and [dubstar-04/Design-Core#61](https://github.com/dubstar-04/Design-Core/pull/61) being merged first

I've broken circles by trying to be clever. I will work out how to fix it.

**Comment by dubstar-04** [comment]
It would be cool if we could change the layer an item is on. More involved but should work.

**Comment by dubstar-04** [comment]
Duplicate of #147

**Pull request closed without merging**
